Added statement to catch and print when and where script fails.
Updated how version searching was done. Original command was failing because golang '404'd' the resource...
Made the command simpler w/ sed.

diff --git a/go-dl b/go-dl
--- a/go-dl
+++ b/go-dl
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
 # Author: Cruz Monrreal II
 
-set -eufo pipefail
+set -eEufo pipefail
+
+on_err() { printf "%s: '%s' failed with '%s'\n" "${1}:${2}" "${3}" "$?" 1>&2; }
+trap 'on_err "${BASH_SOURCE}" "${LINENO}" "${BASH_COMMAND}"' ERR
 
 readonly self_name=${0##*/}
 readonly self_version="0.0.1"
@@ -93,46 +96,38 @@ go version &> /dev/null \
   || die "GOBIN not in PATH."
 
 
-# Fetch/update go release info.
-go get -d "golang.org/dl/..." &> /dev/null \
-  || die "Failed to fetch go release information."
+# Determine full version to download.
+go get -d golang.org/dl/...
 
-
-# Determine which full version to use
-full_version=$(
-  find . -maxdepth 1 -type d ! -name '.*' \
-    | cut -c 3- \
+full_version="$(
+  go list "golang.org/dl/..." 2>/dev/null \
     | sort --version-sort --reverse \
-    | grep ^go${arg_version} \
-    | head -n1 \
-    | sed 's_^go__'
-)
+    | sed -e 's_.*dl/go__g' \
+          -ne '\_'"${arg_version}"'_ { p; q; }' 
+)"
+
 [ -z "${full_version}" ] \
   && die "Requested version not found: '${arg_version}'"
 
 
-# Download, and install, if needed.
-if [ ! -e "${GOPATH}/sdk/go${full_version}" ]; then
+# Download and install.
+info "Downloading v${full_version}"
+go get "golang.org/dl/go${full_version}" &> /dev/null \
+  || die "Download failed"
 
-  info "Downloading v${full_version}"
-  go get "golang.org/dl/go${full_version}" &> /dev/null \
-    || die "Download failed"
+# Note: 'go<version> download' downloads a package into '${HOME}/sdk' with no
+#       option to change the target directory.
+HOME=${GOPATH} "go${full_version}" download &> /dev/null \
+  || die "Download failed"
 
-  # Note: 'go<version> download' downloads a package into '${HOME}/sdk' with no
-  #       option to change the target directory.
-  HOME=${GOPATH} "go${full_version}" download &> /dev/null \
-    || die "Download failed"
-
-  # Generate script to automatically handle setting '${HOME}'
-  mv "${GOPATH}/bin/go${full_version}" "${GOPATH}/bin/_go${full_version}.bin"
-  cat - > "${GOPATH}/bin/go${full_version}" <<EOF
+# Generate script to automatically handle setting '${HOME}'
+mv "${GOPATH}/bin/go${full_version}" "${GOPATH}/bin/_go${full_version}.bin"
+cat - > "${GOPATH}/bin/go${full_version}" <<EOF
 #!/usr/bin/env sh
 HOME="\${GOPATH}" _go${full_version}.bin \$@
 EOF
-  chmod +x "${GOPATH}/bin/go${full_version}"
+chmod +x "${GOPATH}/bin/go${full_version}"
 
-  # Symlink if needed
-  ln -s "${GOPATH}/bin/go${full_version}" "${GOPATH}/bin/go${arg_version}" &> /dev/null \
-    || true
-
-fi
+# Symlink if needed
+ln -s "${GOPATH}/bin/go${full_version}" "${GOPATH}/bin/go${arg_version}" &> /dev/null \
+  || true
